export const AppConfig = {
  name: process.env.NEXT_PUBLIC_APP_NAME || 'Apthex',
  shortName: process.env.NEXT_PUBLIC_APP_SHORT_NAME || 'Aptex',
  description: process.env.NEXT_PUBLIC_APP_DESCRIPTION || 'Aptex Operating System',
  logoUrl: process.env.NEXT_PUBLIC_APP_LOGO_URL || '/apthex-logo-nobg.png',
  iconUrl: process.env.NEXT_PUBLIC_APP_ICON_URL || process.env.NEXT_PUBLIC_APP_LOGO_URL || '/darkicon.ico',
  faviconUrl: process.env.NEXT_PUBLIC_FAVICON_URL || process.env.NEXT_PUBLIC_APP_ICON_URL || process.env.NEXT_PUBLIC_APP_LOGO_URL || '/darkicon.ico',
  themeColor: process.env.NEXT_PUBLIC_THEME_COLOR || '#ff0000ff',
  contactEmail: process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'tanmay@cyberx.org.in',
  orgDomain: process.env.NEXT_PUBLIC_ORGANIZATION_DOMAIN || 'apthex.com',
  prefix: (process.env.NEXT_PUBLIC_APP_SHORT_NAME || 'Aptex').toLowerCase().replace(/[^a-z0-9]/g, ''),
  pwa: {
    name: process.env.NEXT_PUBLIC_PWA_NAME || process.env.NEXT_PUBLIC_APP_NAME || 'Apthex',
    shortName: process.env.NEXT_PUBLIC_PWA_SHORT_NAME || process.env.NEXT_PUBLIC_APP_SHORT_NAME || 'Aptex',
    description: process.env.NEXT_PUBLIC_PWA_DESCRIPTION || process.env.NEXT_PUBLIC_APP_DESCRIPTION || 'Aptex Operating System',
    startUrl: process.env.NEXT_PUBLIC_PWA_START_URL || '/',
    display: (process.env.NEXT_PUBLIC_PWA_DISPLAY as 'standalone' | 'fullscreen' | 'minimal-ui' | 'browser') || 'standalone',
    orientation: (process.env.NEXT_PUBLIC_PWA_ORIENTATION as 'portrait' | 'any' | 'landscape') || 'portrait',
    backgroundColor: process.env.NEXT_PUBLIC_PWA_BG_COLOR || '#080808',
    installTitle: process.env.NEXT_PUBLIC_PWA_INSTALL_PROMPT_TITLE || `Install ${process.env.NEXT_PUBLIC_APP_NAME || 'Apthex'}`,
    installDesc: process.env.NEXT_PUBLIC_PWA_INSTALL_PROMPT_DESC || 'Add to Home Screen for the best experience',
    icons: {
      icon192: process.env.NEXT_PUBLIC_PWA_ICON_192 || '/icon-192.png',
      icon512: process.env.NEXT_PUBLIC_PWA_ICON_512 || '/icon-512.png',
      maskable192: process.env.NEXT_PUBLIC_PWA_ICON_MASKABLE_192 || '/icon-maskable-192.png',
      maskable512: process.env.NEXT_PUBLIC_PWA_ICON_MASKABLE_512 || '/icon-maskable-512.png',
      appleTouch: process.env.NEXT_PUBLIC_PWA_APPLE_TOUCH_ICON || '/apple-icon-180.png',
    },
  },
};
